name: Check Syntax and Run Tests

on:
  push:
    branches:
      - main

jobs:
  check-syntax-and-run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        python -m pip install unittest

    - name: Display Python version
      run: |
        python --version

    - name: Run flake8
      run: |
        flake8

    - name: Run unittests
      run: |
        python -m unittest discover -v
